# Generated by Django 5.2.11 on 2026-02-26 00:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=180)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Notebook', max_length=60)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('numero_serie', models.CharField(blank=True, max_length=120)),
                ('observaciones_ingreso', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='taller.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema_reportado', models.TextField()),
                ('diagnostico', models.TextField(blank=True)),
                ('precio_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('EN_REVISION', 'En revisión'), ('PRESUPUESTADO', 'Presupuestado'), ('REPARANDO', 'Reparando'), ('REPARADO', 'Reparado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='INGRESADO', max_length=20)),
                ('stock_descontado', models.BooleanField(default=False)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_imagen', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='taller.equipo')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='taller.ordenreparacion')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.repuesto')),
            ],
        ),
    ]
